### ISSUE TITLE
Addon nach update disabled

### ISSUE THREAD

**Issue by multeam3dia** [watchone/repository.xship#11]
Hab auf mehreren Geräten das Problem, dass xship erstmal disabled ist, sobald sich das addon aktualisiert hat.
Andere Addons haben das Problem nicht. Muss ich was umstellen, um das zu beheben?

**Comment by watchone** [comment]
fehlende Angaben zum Betriebssysten, Kodiversion und xShip Version.
Verhalten kann nicht nachgestellt werden

**Comment by TitanME** [comment]
Das ist allerdings ein Problem, welches in allen FB-Gruppen so im Abstand von ca. 2 Tagen immer und immer wieder auftaucht!
Absolutes Dauer-Problem etlicher User!

- OS unabhängig
- Xship-Version unabhängig
- hauptsächlich Matrix
