### ISSUE TITLE
keine Quellen von Serienstream nach update

### ISSUE THREAD

**Issue by neires** [watchone/repository.xship#12]
Kodi-Version: Matrix 19.3

Serie: alle z.B Titans (2018)

Nach dem update auf plugin.video.xship-2022.01.13 werden keine Quellen von Serienstream gefunden.
Ich habe dann wieder die plugin.video.xship-2022.01.10 eingespielt und es wurde wieder Quellen gefunden.

Ich sehe das es in der serienstream.py Änderungen an der "def run" gab und es eine neue "def run2" gibt.
Die def run mit dem aLinks scheint nicht richtig zu arbeiten ;)

**Comment by watchone** [comment]
Danke für die sehr gut geschriebene Fehlermeldung!

Das Problem sollte gelöst sein. 
Über "Aus Repository installieren / xShip Repository / Video-Addons / Xship / Version bzw.Aktualisieren die Version noch mal installieren.
