### ISSUE TITLE
Probleme mit Xship und Sereinstream

### ISSUE THREAD

**Issue by Yaqwa** [watchone/repository.xship#2]
habe einige SErien die PRobleme bereiten. Leverage 2.0 z.B. auf xship geht es nicht auf xstream /serienstream findet er 3 Quellen auf Deutsch und natürlich auch die englischen - aber eben 3 DE Quellen. Probleme mit Xship und Sereinstream?

**Comment by kasi45** [comment]
![Unbenannt](https://user-images.githubusercontent.com/18262216/141534197-0d1f4d71-fd3b-4d9e-94c5-fe7899e446cd.JPG)
