### ISSUE TITLE
Fortsetzungspunkte/Watchstates in Xship

### ISSUE THREAD

**Issue by TitanME** [watchone/repository.xship#3]
Xship scheint im Gegensatz zu xStream keine Fortsetzungspunkte zu setzen, obwohl in den Einstellungen dazu gleich 2 verschiedene Optionen vorhanden sind.
Jede Serie/Film startet immer wieder von vorn.

Watchstates sind eine Kodi-Interne Funktion, muss aber vom Addon unterstützt werden. Gibt es da eine Möglichkeit, dies auch bei Xship zu realisieren?

**Comment by watchone** [comment]
![Unbenannt](https://user-images.githubusercontent.com/82899367/142772630-5fbe89bf-e20a-45f1-93bb-cd8135f7bca1.JPG)

meinst du dies?

**Comment by TitanME** [comment]
Ja genau...funktioniert bei mir nicht. Eventuell eine Einstellungssache oder anbieter-abhängig?

**Comment by watchone** [comment]
Und wie immer die Nachfrage nach dem verwendeten Versionen vom BS, Kodi und xShip.

"seekTime" ist die Eigenschaft die der Kodi Player nutzt um zu einer Stelle im Film zu springen.
xShip setzt einen Wert für diese Eigenschaft erst wenn der Film/Episode vorher schon mal länger als 3 Minuten lief. Ansonst start vom Stream von Anfang

**Comment by TitanME** [comment]
Getestet auf:

- Windows
- Kodi **19.3**
- Xship 2021.11.21~nightly1

- Android
- Kodi **19.3**
- Xship 2021.11.21~nightly1

Xship > Serien > Am populärsten > Foundation > Staffel1 > Folge1 > Stream 5 min. laufen lassen > gestoppt > Folge1 erneut aufgerufen > denselben Anbieter & Hoster genommen (Kinoger/FSST) > **Stream startet wieder am Anfang**
____________________________________________________________________________

- Windows
- Kodi **18.9**
- Xship 2021.11.21~nightly1

- Android
- Kodi **18.9**
- Xship 2021.11.21~nightly1

Xship > Serien > Am populärsten > Foundation > Staffel1 > Folge1 > Stream 5 min. laufen lassen > gestoppt > Folge1 erneut aufgerufen > denselben Anbieter & Hoster genommen (Kinoger/FSST) > **FUNKTIONIERT**


![A5](https://user-images.githubusercontent.com/65415236/142878608-d78fbb41-54c4-46fa-905f-37d461ca7fbb.jpg)
____________________________________________________________________________

Fortsetzungspunkte funktionieren bei **xStream** (selbe Serie/Staffel/Folge/Anbieter/Hoster) auf Kodi 18 **UND** 19 !

Scheint ein Xship/Matrix-Problem zu sein.

**Comment by watchone** [comment]
Mit der schönen Beschreibung hätte ich das schon vor 3 Tagen patchen können ;-)
Ist nun auch für Matrix verfügbar!

**Comment by TitanME** [comment]
Danke dir...funktioniert 👍
