### ISSUE TITLE
Seiten schalten sich selbständig ab.

### ISSUE THREAD

**Issue by Klops83** [watchone/repository.xship#4]
Hi hab das problem das wenn ich bei einem film oder einer serie die streams suchen lass das dann einige seiten ausgeschaltet werden.
Ich geh ich die einstellungen von xship und aktiviere alle seiten für die suche. Bestätige mit ok. Such nochmal ein film oder eine serie und es werden keine streams von zb. Kinox gefunden(obwohl ich weiß das der film da vorhanden ist) geh danach wieder in die einstellungen und sehe da die seite hat sich deaktiviert. Warum ist das so?
Kodi 19.3 unter android

**Comment by Klops83** [comment]
Unter kodi 18.9 gehen aus 2 seiten von selber aus. Es sind folgende seiten...

Unter kodi 18.9
KKiste.movie
Movie4K click

Und unter 19.3
KKiste.movie
Movie4K.click
Kinox.to

Vielleicht findet ihr ja den fehler.

**Comment by watchone** [comment]
wenn ein Scraper einen gravierenden Fehler hat ist das Abschalten gewollt um nicht den Ablauf im Addon zu blockieren.

die von dir genannten Scraper müssen aktualisiert werden

**Comment by watchone** [comment]
Die Scraper sind angepasst.
Danke für die Hinweise!

**Comment by TitanME** [comment]
Werden die angepassten Scarper/Indexseiten nach erfolgreicher Anpassung denn wieder automatisch aktiviert in den Einstellungen oder muss der User das selbst machen? Nach meiner Erfahrung muss man das wohl selbst machen, oder?

Wäre da nicht eine Auswahl-Option besser?

**Defekte Indexseiten automatisch deaktivieren**

Die Option kann man dann in den Einstellungen selbst aktivieren oder deaktivieren

**Comment by watchone** [comment]
> Werden die angepassten Scarper/Indexseiten nach erfolgreicher Anpassung denn wieder automatisch aktiviert in den Einstellungen oder muss der User das selbst machen? Nach meiner Erfahrung muss man das wohl selbst machen, oder?

Genau so ist es. Es gibt kein Kriterium um zu unterscheiden ob der Nutzer einen Scraper deaktiviert oder ob durch einen Error zb. importfehler von einem Python modul / Fehler durch geänderte Html der Indexseite der Scraper deaktiviert wurde.
Somit ist auch keine Auswahloption möglich. "knallt es" - egal aus welchem Grund im Source - wird abgeschaltet.

**Comment by TitanME** [comment]
Ja, das verstehe ich natürlich.
Andersherum bei einem User, der eigentlich alle Anbieter aktiviert hat, kann es also sein, dass sein Xship nach und nach immer weniger Anbieter aktiviert hat und er das eigentlich gar nicht mit bekommt, richtig?

Da müsste man den Leuten ja empfehlen, sich ab und zu mal die Einstellungen anzuschauen, ob überhaupt noch alle bzw. die gewünschten Indexseiten aktiviert sind. Wenn er/sie den Anbieter dann einfach wieder aktiviert...eine Suche im Addon ausführt und der Anbieter sich anschließend WIEDER deaktiviert hat, dann kann er davon ausgehen, dass der entsprechende Scraper defekt ist und angepasst werden muss, oder? Spätestens jetzt kann er den Anbieter hier z.B. als defekt melden.
