### ISSUE TITLE
TMDB-search is not showing results as expected

### ISSUE THREAD

**Issue by CarstenG2** [watchone/repository.xship#6]
Here a direct search: https://www.themoviedb.org/search?query=es+ist+nur+eine+phase
Same phrase "es ist nur eine phase" does not return anything in Movie-Search. 
Url-Encode?

**Comment by CarstenG2** [comment]
Also here a sample of the TMDB-API call: 
https://api.themoviedb.org/3/search/movie?api_key={api_key}&query=es+ist+nur+eine+phase

**Comment by watchone** [comment]
Und wie immer die Nachfrage nach den verwendeten Versionen vom BS, Kodi und xShip.

**Comment by watchone** [comment]
xShip findet in TMDB den Film "es ist nur eine phase" - der wird aber nicht angezeigt weil er NOCH nicht die Bedingungen im Filter von xShip erfüllt. (vote_count < 10) Es gibt dazu auch noch keinen Stream.

**Comment by CarstenG2** [comment]
searching for above film still does not work. how can I check the vote-count? how can I remove this additional vote-count filter? or do I need to put the search-string into single/double quotes in any way?
