### ISSUE TITLE
IMDb User-ID unter Konten

### ISSUE THREAD

**Issue by TitanME** [watchone/repository.xship#7]
Wäre es wohl möglich, in Xship wieder IMDb-User-ID's unter Konten einzutragen...so wie es bei Lasthip früher möglich war?

Da gibt es viele TMDb-User, die top sortierte Filmlisten erstellen (öffentlich)...TOP250 Action-Movies...Top Weihnachtsfilme...80's Movies...400 Movies based on true story...Jackie Chan Movies...Best Kids Movies...Disney Movies...usw.

![IMDB User ID 50382990](https://user-images.githubusercontent.com/65415236/143494087-baeafc50-838e-4079-aff1-f5443d1abe60.jpg)

**Comment by watchone** [comment]
xShip benutzt IMDB nicht. (oder war IMDB ein Schreibfehler von dir?)
Es gibt auch sonst für keine DB eine keine Anbindung für persönliche Listen und es ist auch nicht geplant dies umzusetzen
Die einzig existierende Schnittstelle ist für das Plugin "Video Themoviedb Helper" (xship.json) In dem Plugin kann man, so weit wie mir bekannt ist, persönliche Listen einbinden.

**Comment by TitanME** [comment]
Nein, IMDb war schon ernst gemeint...war halt früher in Lastship drin (siehe Screenshot)

Aber wenn es eh nicht geplant ist, kann hier zu 😉
